### ISSUE TITLE
Lets Talk about teams 

### ISSUE THREAD

**Issue by tomlazar** [2202Programming/Documents#3]
Right now we have three main github teams.

**developers**: all the developers on the team.
**leads**: David and Daniel for right now
**controls**: For Gage and his marry band of cohorts

Area their any other teams we should add/ are these good teams.

@aaron97neu @2202Programming/leads @Whissp

**Comment by SecondThread** [comment]
We may need a mechanical and or business team too

**Comment by aaron97neu** [comment]
Not sure what the mechanical team would do with github...

**Comment by tomlazar** [comment]
the focus has been on issues and the new projects features, using them to keep track of what people are working on.

[like this](https://github.com/2202Programming/Documents/projects/1)
